[package]
name = "tosd-client"
version = "1.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
zbus = { version = "3", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
