// external modules
import { Button, VerticalBox } from "std-widgets.slint";

// local modules
import { ThemeManager } from "style.slint";

export { ThemeManager } // reexport to rust

export component AppWindow inherits Window {
    title: "Theom Dashboard";
    min-width: 500px;
    min-height: 400px;
    background: ThemeManager.background-color;

    in-out property <string> user: "unknown user";
    
    in property <length> screen-width: 800px;

    callback set_uptime();
    in property<string> uptime;

    callback get_time() -> string;
    property<string> currenttime: "0:00";

    Timer {
        interval: 100ms;
        running: true;
        triggered() => {
            root.currenttime = root.get_time();
            self.running = false;
        }
    }

    Timer {
        interval: 1s;
        running: true;
        triggered() => {
            root.currenttime = root.get_time();
        }
    }

    GridLayout {
        spacing: 5px;
        padding: 4px;

        // Greeter
        Rectangle {
            col: 0;
            row: 0;
            border-radius: 8px;
            background: ThemeManager.content-bg-color;
            height: 20%;
            width: 35%;

            VerticalLayout {
                property <length> heading-font-size: { (root.screen-width / 35px) * 1px }
                property <length> subheading-font-size: { (root.screen-width / 50px) * 1px }
                Text {
                    text: "Hello";
                    horizontal-alignment: center;
                    font-size: heading-font-size;
                    font-weight: 800;
                    color: ThemeManager.text-color;
                }

                Text {
                    text: "\{root.user}!";
                    font-size: subheading-font-size;
                    font-weight: 500;
                    horizontal-alignment: center;
                    color: ThemeManager.text-color;
                }
            }
        }

        // time
        Rectangle {
            col: 1;
            row: 0;
            colspan: 3;
            border-radius: 8px;
            padding: 10px;
            background: ThemeManager.content-bg-color;
            Text {
                text: "\{root.currenttime}";
                color: ThemeManager.text-color;
            }
        }

        // Music control
        Rectangle {
            col: 0;
            row: 1;
            rowspan: 2;
            border-radius: 8px;
            padding: 10px;
            background: ThemeManager.content-bg-color;

            Text {
                text: "Music playing";
                color: ThemeManager.text-color;
            }

            // Image {
            //     source: @image-url("Previous.svg");
            //     width: 24px; height: 24px;
            // }

            // Image {
            //     source: @image-url("play.svg");
            //     width: 24px; height: 24px;
            // }

            // Image {
            //     source: @image-url("Next.svg");
            //     width: 24px; height: 24px;
            // }
        }

        Rectangle {
            col: 1;
            row: 1;
            colspan: 3;
            rowspan: 1;
            border-radius: 8px;
            background: ThemeManager.content-bg-color;
        }

        Rectangle {
            col: 1;
            row: 2;
            colspan: 3;
            rowspan: 1;
            border-radius: 8px;
            background: ThemeManager.content-bg-color;
        }
    }
}