#!/usr/bin/env python3

import argparse
from pydbus import SessionBus

def main():
    parser = argparse.ArgumentParser(description="tosd CLI client to call D-Bus server")
    parser.add_argument("text", nargs="?", help="Text label or 'clear'")
    parser.add_argument("mode", nargs="?", choices=["slider", "text"], help="Display mode")
    parser.add_argument("value", nargs="?", type=int, help="Value for slider or text")
    # Only parse these if not clearing
    parser.add_argument("-d", "--duration", type=float, default=2.0)
    parser.add_argument("-s", "--size", type=float, default=1.0)
    parser.add_argument("-p", "--position", type=str, default="T")
    parser.add_argument("-r", "--reuse-window", action="store_true", help="Reuse the current OSD window if available.")
    parser.add_argument("--background-color", type=str, default="#23262d")
    parser.add_argument("--text-color", type=str, default="#ffffff")
    parser.add_argument("--slider-fill-color", type=str, default="#61afef")
    parser.add_argument("--slider-knob-color", type=str, default="#528bff")

    args = parser.parse_args()

    bus = SessionBus()
    proxy = bus.get("org.theom.tosd", "/org/theom/tosd")

    if args.text == "clear":
        proxy.ClearAll()
        return

    proxy.ShowOSD(args.text, args.mode, args.value, args.duration, args.size, args.position, args.reuse_window,
                  args.background_color, args.text_color, args.slider_fill_color, args.slider_knob_color)


if __name__ == "__main__":
    main()
